baseURL = "https://localhost:1313/"
title   = "ğŸ¼ ä¹è°±å¤§å…¨"
theme   = "book"

# Book configuration
disablePathToLower = true
enableGitInfo      = true

# Needed for mermaid/katex shortcodes
[markup]
    [markup.goldmark.renderer]
        unsafe = true

[markup.tableOfContents]
    startLevel = 1

[languages]
    [languages.zh]
        languageName = 'ä¸­æ–‡'
        contentDir   = 'content'
        weight       = 1
    [languages.en]
        languageName = 'English'
        contentDir   = 'content.en'
        weight       = 2
    [languages.ru]
        languageName = 'Ğ ÑƒÑÑĞºĞ¸Ğ¹'
        contentDir   = 'content.ru'
        weight       = 3

[menu]
    [[menu.after]]
        name   = "ğŸ”— æ·˜å®åº—é“º"
        url    = "/"
        weight = 50

[params]
    BookTheme          = 'light'
    BookToC            = true
    BookSection        = 'docs'
    BookDateFormat     = 'January 1, 2022'
    BookSearch         = true
    BookComments       = true
    BookPortableLinks  = true
    BookServiceWorker  = true
    BookTranslatedOnly = false
